#ifndef DataFormats_SiPixelGainCalibrationForHLTSoA_src_classes_h
#define DataFormats_SiPixelGainCalibrationForHLTSoA_src_classes_h

#include "DataFormats/SiPixelMappingSoA/interface/SiPixelMappingLayout.h"

#endif  // DataFormats_SiPixelGainCalibrationForHLTSoA_src_classes_h
