#ifndef DataFormats_SiPixelGainCalibrationForHLTPortable_Alpaka_src_Classes_serial_h
#define DataFormats_SiPixelGainCalibrationForHLTPortable_Alpaka_src_Classes_serial_h

#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/Portable/interface/Product.h"
#include "DataFormats/SiPixelGainCalibrationForHLTSoA/interface/SiPixelGainCalibrationForHLTLayout.h"
#include "DataFormats/SiPixelGainCalibrationForHLTSoA/interface/SiPixelGainCalibrationForHLTHost.h"

#endif  // DataFormats_SiPixelGainCalibrationForHLTSoA_Alpaka_src_Classes_serial_h
