#ifndef DataFormats_SiPixelGainCalibrationForHLTSoA_Alpaka_Classes_CUDA_h
#define DataFormats_SiPixelGainCalibrationForHLTSoA_Alpaka_Classes_CUDA_h

#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/Portable/interface/Product.h"
#include "DataFormats/SiPixelGainCalibrationForHLTSoA/interface/SiPixelGainCalibrationForHLTLayout.h"
#include "DataFormats/SiPixelGainCalibrationForHLTSoA/interface/alpaka/SiPixelGainCalibrationForHLTDevice.h"

#endif  // DataFormats_SiPixelGainCalibrationForHLTSoA_Alpaka_Classes_Device_h
