#include "tdrstyle.C"
#include "CMS_lumi.C"

using namespace std;

double errorCalc(Int_t x, Int_t y){
    double dx = sqrt(x);
    double dy = sqrt(y);
    return (1/(double) y)*(dx + (((double) x/(double) y)*dy));
}

void create_efficiencies(std::string lifetime, std::string outputDir)
{

    setTDRStyle();
    gStyle->SetOptStat(0);
    writeExtraText = true;
    extraText = "Simulation";
    lumi_sqrtS = "Signal MC, 13.6 TeV";
    std::string inputFile = "outputFile" + lifetime + ".root";
    TFile *f = TFile::Open(inputFile.c_str());
    TH1 *den1;
    TH1 *den2;
    TH1 *den4;
    TH1 *den5;
    TH1 *den12;
    TH1 *den22;
    TH1 *den42;
    TH1 *den52;
    f->GetObject("triggerSignalAnalyzer/4pfmet105", den1);
    f->GetObject("triggerSignalAnalyzer/5pfmet105", den2);
    f->GetObject("triggerSignalAnalyzer/6pfmet105", den4);
    f->GetObject("triggerSignalAnalyzer/pfmet105", den5);
    f->GetObject("triggerSignalAnalyzer/1204pfmet105", den12);
    f->GetObject("triggerSignalAnalyzer/1205pfmet105", den22);
    f->GetObject("triggerSignalAnalyzer/1206pfmet105", den42);
    f->GetObject("triggerSignalAnalyzer/120pfmet105", den52);
    TH1 *num1;
    TH1 *num2;
    TH1 *num4;
    TH1 *num5;
    TH1 *num12;
    TH1 *num22;
    TH1 *num42;
    TH1 *num52;
    f->GetObject("triggerSignalAnalyzer/4hltpfmet105", num1);
    f->GetObject("triggerSignalAnalyzer/5hltpfmet105", num2);
    f->GetObject("triggerSignalAnalyzer/6hltpfmet105", num4);
    f->GetObject("triggerSignalAnalyzer/hltpfmet105", num5);
    f->GetObject("triggerSignalAnalyzer/1204hltpfmet105", num12);
    f->GetObject("triggerSignalAnalyzer/1205hltpfmet105", num22);
    f->GetObject("triggerSignalAnalyzer/1206hltpfmet105", num42);
    f->GetObject("triggerSignalAnalyzer/120hltpfmet105", num52);
    
    int marker = 20;
    const char *ylabel = "Trigger Efficiency";
    const char *xlabelnomu = "PF E_{T}^{miss, no mu}";
    const char *xlabelyemu = "PF E_{T}^{miss}";
    float ymin = 0.0;
    float ymax = 1.2;
    float xmin = 0.0;
    float xmax = 1000.0;
    TLine *l = new TLine(xmin, 1.0, xmax, 1.0);
    l->SetLineStyle(7);
    l->SetLineWidth(2);
    float x0 = 0.1891;
    float x1 = 0.3395;
    float y0 = 0.8592;
    float y1 = 0.9214;

    TCanvas *c1 = new TCanvas("c1", "c1", 700, 700);
    TCanvas *c2 = new TCanvas("c2", "c2", 700, 700);
    TCanvas *c4 = new TCanvas("c4", "c4", 700, 700);
    TCanvas *c5 = new TCanvas("c5", "c5", 700, 700);
    TCanvas *c12 = new TCanvas("c12", "c12", 700, 700);
    TCanvas *c22 = new TCanvas("c22", "c22", 700, 700);
    TCanvas *c42 = new TCanvas("c42", "c42", 700, 700);
    TCanvas *c52 = new TCanvas("c52", "c52", 700, 700);
    TCanvas *cesp = new TCanvas("cesp", "cesp", 700, 700);
    
    std::string outFile = outputDir + "/" + lifetime+ "_hlt_efficiencies.root";
    TFile *file = new TFile(outFile.c_str(), "RECREATE");

    TGraphAsymmErrors *pEff1 = new TGraphAsymmErrors("4pfmet105");
    pEff1->SetTitle("4 layers - HLT_MET105_IsoTrk50_v");
    pEff1->Divide(num1, den1);
    pEff1->SetTitle("");
    pEff1->SetMarkerStyle(marker);
    pEff1->GetHistogram()->SetMinimum(ymin);
    pEff1->GetHistogram()->SetMaximum(ymax);
    pEff1->GetYaxis()->SetTitle(ylabel);
    pEff1->GetXaxis()->SetTitle(xlabelnomu);
    pEff1->GetYaxis()->SetTitleSize(0.04);
    pEff1->GetXaxis()->SetTitleSize(0.04);
    pEff1->GetYaxis()->SetLabelSize(0.04);
    pEff1->GetXaxis()->SetLabelSize(0.04);
    pEff1->GetXaxis()->SetLimits(xmin, xmax);
    auto legend1 = new TLegend(x0, y0, x1, y1);
    legend1->AddEntry(pEff1, "HLT_MET105_IsoTrk50_v*", "");
    legend1->SetLineWidth(0);
    legend1->SetTextSize(0.02559);
    legend1->SetBorderSize(0);
    legend1->SetTextFont(42);
    c1->cd();
    pEff1->Draw("ap");
    legend1->Draw();
    l->Draw();
    CMS_lumi(c1, 0, 0);
    c1->Write();
    pEff1->Write();
    std::string outMET1054 = outputDir + "/" + lifetime+ "_4Layers_HLT_MET105_IsoTrk50_v.pdf";
    c1->Print(outMET1054.c_str());
    
    TGraphAsymmErrors *pEff2 = new TGraphAsymmErrors("5pfmet105");
    pEff2->SetTitle("5 layers - HLT_MET105_IsoTrk50_v");
    pEff2->Divide(num2, den2);
    pEff2->SetTitle("");
    pEff2->SetMarkerStyle(marker);
    pEff2->GetHistogram()->SetMinimum(ymin);
    pEff2->GetHistogram()->SetMaximum(ymax);
    pEff2->GetYaxis()->SetTitle(ylabel);
    pEff2->GetXaxis()->SetTitle(xlabelyemu);
    pEff2->GetYaxis()->SetTitleSize(0.04);
    pEff2->GetXaxis()->SetTitleSize(0.04);
    pEff2->GetYaxis()->SetLabelSize(0.04);
    pEff2->GetXaxis()->SetLabelSize(0.04);
    pEff2->GetXaxis()->SetLimits(xmin, xmax);
    auto legend2 = new TLegend(x0, y0, x1, y1);
    legend2->AddEntry(pEff1, "HLT_MET105_IsoTrk50_v*", "");
    legend2->SetLineWidth(0);
    legend2->SetTextSize(0.02559);
    legend2->SetBorderSize(0);
    legend2->SetTextFont(42);
    c2->cd();
    pEff2->Draw("ap");
    legend2->Draw();
    l->Draw();
    CMS_lumi(c2, 0, 0);
    c2->Write();
    pEff2->Write();
    std::string outMET1055 = outputDir + "/" + lifetime+ "_5Layers_HLT_MET105_IsoTrk50_v.pdf";
    c2->Print(outMET1055.c_str());

    TGraphAsymmErrors *pEff4 = new TGraphAsymmErrors("6pfmet105");
    pEff4->SetTitle("6 plus layers - HLT_MET105_IsoTrk50_v");
    pEff4->Divide(num4, den4);
    pEff4->SetTitle("");
    pEff4->SetMarkerStyle(marker);
    pEff4->GetHistogram()->SetMinimum(ymin);
    pEff4->GetHistogram()->SetMaximum(ymax);
    pEff4->GetYaxis()->SetTitle(ylabel);
    pEff4->GetXaxis()->SetTitle(xlabelnomu);
    pEff4->GetYaxis()->SetTitleSize(0.04);
    pEff4->GetXaxis()->SetTitleSize(0.04);
    pEff4->GetYaxis()->SetLabelSize(0.04);
    pEff4->GetXaxis()->SetLabelSize(0.04);
    pEff4->GetXaxis()->SetLimits(xmin, xmax);
    auto legend4 = new TLegend(x0, y0, x1, y1);
    legend4->AddEntry(pEff1, "HLT_MET105_IsoTrk50_v*", "");
    legend4->SetLineWidth(0);
    legend4->SetTextSize(0.02559);
    legend4->SetBorderSize(0);
    legend4->SetTextFont(42);
    c4->cd();
    pEff4->Draw("ap");
    legend4->Draw();
    l->Draw();
    CMS_lumi(c4, 0, 0);
    c4->Write();
    pEff4->Write();
    std::string outMET1056 = outputDir + "/" + lifetime+ "_6pLayers_HLT_MET105_IsoTrk50_v.pdf";
    c4->Print(outMET1056.c_str());

    TGraphAsymmErrors *pEff5 = new TGraphAsymmErrors("pfmet105");
    pEff5->SetTitle("HLT_MET105_IsoTrk50_v");
    pEff5->Divide(num5, den5);
    pEff5->SetTitle("");
    pEff5->SetMarkerStyle(marker);
    pEff5->GetHistogram()->SetMinimum(ymin);
    pEff5->GetHistogram()->SetMaximum(ymax);
    pEff5->GetYaxis()->SetTitle(ylabel);
    pEff5->GetXaxis()->SetTitle(xlabelnomu);
    pEff5->GetYaxis()->SetTitleSize(0.04);
    pEff5->GetXaxis()->SetTitleSize(0.04);
    pEff5->GetYaxis()->SetLabelSize(0.04);
    pEff5->GetXaxis()->SetLabelSize(0.04);
    pEff5->GetXaxis()->SetLimits(xmin, xmax);
    auto legend5 = new TLegend(x0, y0, x1, y1);
    legend5->AddEntry(pEff1, "HLT_MET105_IsoTrk50_v*", "");
    legend5->AddEntry(pEff1, "AMSB - 700 GeV", "p");
    legend5->SetLineWidth(0);
    legend5->SetTextSize(0.02559);
    legend5->SetBorderSize(0);
    legend5->SetTextFont(42);
    c5->cd();
    pEff5->Draw("ap");
    legend5->Draw();
    l->Draw();
    CMS_lumi(c5, 0, 0);
    c5->Write();
    pEff5->Write();
    std::string outMET105 = outputDir + "/" + lifetime+ "_HLT_MET105_IsoTrk50_v.pdf";
    c5->Print(outMET105.c_str());

    TGraphAsymmErrors *pEff12 = new TGraphAsymmErrors("1204pfmet105");
    pEff12->SetTitle("4 layers - HLT_MET105_IsoTrk50_v");
    pEff12->Divide(num12, den12);
    pEff12->SetTitle("");
    pEff12->SetMarkerStyle(marker);
    pEff12->GetHistogram()->SetMinimum(ymin);
    pEff12->GetHistogram()->SetMaximum(ymax);
    pEff12->GetYaxis()->SetTitle(ylabel);
    pEff12->GetXaxis()->SetTitle(xlabelnomu);
    pEff12->GetYaxis()->SetTitleSize(0.04);
    pEff12->GetXaxis()->SetTitleSize(0.04);
    pEff12->GetYaxis()->SetLabelSize(0.04);
    pEff12->GetXaxis()->SetLabelSize(0.04);
    pEff12->GetXaxis()->SetLimits(xmin, xmax);
    c12->cd();
    pEff12->Draw("ap");
    legend1->Draw();
    l->Draw();
    CMS_lumi(c12, 0, 0);
    c12->Write();
    pEff12->Write();
    std::string outMET10542 = outputDir + "/" + lifetime+ "_120METCut_4Layers_HLT_MET105_IsoTrk50_v.pdf";
    c12->Print(outMET10542.c_str());
    
    TGraphAsymmErrors *pEff22 = new TGraphAsymmErrors("1205pfmet105");
    pEff22->SetTitle("5 layers - HLT_MET105_IsoTrk50_v");
    pEff22->Divide(num22, den22);
    pEff22->SetTitle("");
    pEff22->SetMarkerStyle(marker);
    pEff22->GetHistogram()->SetMinimum(ymin);
    pEff22->GetHistogram()->SetMaximum(ymax);
    pEff22->GetYaxis()->SetTitle(ylabel);
    pEff22->GetXaxis()->SetTitle(xlabelyemu);
    pEff22->GetYaxis()->SetTitleSize(0.04);
    pEff22->GetXaxis()->SetTitleSize(0.04);
    pEff22->GetYaxis()->SetLabelSize(0.04);
    pEff22->GetXaxis()->SetLabelSize(0.04);
    pEff22->GetXaxis()->SetLimits(xmin, xmax);
    c22->cd();
    pEff22->Draw("ap");
    legend2->Draw();
    l->Draw();
    CMS_lumi(c22, 0, 0);
    c22->Write();
    pEff22->Write();
    std::string outMET10552 = outputDir + "/" + lifetime+ "_120METCut_5Layers_HLT_MET105_IsoTrk50_v.pdf";
    c22->Print(outMET10552.c_str());

    TGraphAsymmErrors *pEff42 = new TGraphAsymmErrors("1206pfmet105");
    pEff42->SetTitle("6 plus layers - HLT_MET105_IsoTrk50_v");
    pEff42->Divide(num42, den42);
    pEff42->SetTitle("");
    pEff42->SetMarkerStyle(marker);
    pEff42->GetHistogram()->SetMinimum(ymin);
    pEff42->GetHistogram()->SetMaximum(ymax);
    pEff42->GetYaxis()->SetTitle(ylabel);
    pEff42->GetXaxis()->SetTitle(xlabelnomu);
    pEff42->GetYaxis()->SetTitleSize(0.04);
    pEff42->GetXaxis()->SetTitleSize(0.04);
    pEff42->GetYaxis()->SetLabelSize(0.04);
    pEff42->GetXaxis()->SetLabelSize(0.04);
    pEff42->GetXaxis()->SetLimits(xmin, xmax);
    c42->cd();
    pEff42->Draw("ap");
    legend4->Draw();
    l->Draw();
    CMS_lumi(c42, 0, 0);
    c42->Write();
    pEff42->Write();
    std::string outMET10562 = outputDir + "/" + lifetime+ "_120METCut_6pLayers_HLT_MET105_IsoTrk50_v.pdf";
    c42->Print(outMET10562.c_str());

    TGraphAsymmErrors *pEff52 = new TGraphAsymmErrors("120pfmet105");
    pEff52->SetTitle("HLT_MET105_IsoTrk50_v");
    pEff52->Divide(num52, den52);
    pEff52->SetTitle("");
    pEff52->SetMarkerStyle(marker);
    pEff52->GetHistogram()->SetMinimum(ymin);
    pEff52->GetHistogram()->SetMaximum(ymax);
    pEff52->GetYaxis()->SetTitle(ylabel);
    pEff52->GetXaxis()->SetTitle(xlabelnomu);
    pEff52->GetYaxis()->SetTitleSize(0.04);
    pEff52->GetXaxis()->SetTitleSize(0.04);
    pEff52->GetYaxis()->SetLabelSize(0.04);
    pEff52->GetXaxis()->SetLabelSize(0.04);
    pEff52->GetXaxis()->SetLimits(xmin, xmax);
    c52->cd();
    pEff52->Draw("ap");
    legend5->Draw();
    l->Draw();
    CMS_lumi(c52, 0, 0);
    c52->Write();
    pEff52->Write();
    std::string outMET1052 = outputDir + "/" + lifetime+ "_120METCut_HLT_MET105_IsoTrk50_v.pdf";
    c52->Print(outMET1052.c_str());

    cesp->cd();
    auto overallEff = new TH1D("overallEff","",4,-0.5,3.5);
    overallEff->Fill(0.,num12->TH1::Integral()/den12->TH1::Integral());
    overallEff->Fill(1.,num22->TH1::Integral()/den22->TH1::Integral());
    overallEff->Fill(2.,num42->TH1::Integral()/den42->TH1::Integral());
    overallEff->Fill(3.,num52->TH1::Integral()/den52->TH1::Integral());
    overallEff->GetXaxis()->SetBinLabel(1,"4Layers");
    overallEff->GetXaxis()->SetBinLabel(2,"5Layers");
    overallEff->GetXaxis()->SetBinLabel(3,"6PlusLayers");
    overallEff->GetXaxis()->SetBinLabel(4,"Total");
    overallEff->SetBinError(1,errorCalc(num12->TH1::Integral(),den12->TH1::Integral()));
    overallEff->SetBinError(2,errorCalc(num22->TH1::Integral(),den22->TH1::Integral()));
    overallEff->SetBinError(3,errorCalc(num42->TH1::Integral(),den42->TH1::Integral()));
    overallEff->SetBinError(4,errorCalc(num52->TH1::Integral(),den52->TH1::Integral()));
    overallEff->GetYaxis()->SetRangeUser(0.0,1.0);
    overallEff->Draw();
    CMS_lumi(cesp, 0, 0);
    cesp->Write();
    overallEff->Write();
    std::string outMET105esp = outputDir + "/" + lifetime+ "_120METCut_overall_HLT_MET105_IsoTrk50_v.pdf";
    cesp->Print(outMET105esp.c_str());

    f->Close();
    file->Close();
}